### ISSUE TITLE
ODF 1.3 Appendix G Appendix GChanges From ODF 1.2 (Non Normative) seems incomplete

### ISSUE THREAD

**Issue by svanteschubert** [oasis-tcs/odf-tc#36] opened 2021-02-01 18:30 UTC
We started discussing this issue in our ODF TC call today:
https://lists.oasis-open.org/archives/office/202102/msg00004.html

Of the 11 deprecations 5 are not being listed at all.
The other are listed somewhere but not under deprecations.
5.3.6 <text:numbered-paragraph> (deprecated)listed in Changes Appendix under Changed elements, office-1437
5.3.7 Numbered Paragraph Style Rules (deprecated)Not listed
10.4.7 <draw:applet> (Deprecated)listed under Changed Elements
10.8.4 <presentation:show-text> (deprecated)Not listed
19.815.2 <draw:text-box> (deprecated)an attribute of it changed
19.815.5 <text:changed-region> (deprecated)Not listed
19.815.6 <text:h> (deprecated)Not listed
19.815.8 <text> (deprecated)Not listed
19.835 text:list-id (deprecated)listed under Changed Attributes
19.874.6 <text:numbered-paragraph> (deprecated)listed under changes for text:start-value, office-1437
19.880.25 <text:numbered-paragraph> (deprecated)listed under Changes for text:style-name, office-1437

We should also fix 
 the variable capitalization of deprecated/Deprecated in headings
 the variable use of parentheses.

**Comment by mistmist** [comment] 2021-02-08 17:12
this is duplicate of #37 => closed

**Closed** 2021-02-08 17:11 UTC
Labels: editorial
